/*          Copyright Ubiquiti Networks Inc. 2014
**          All Rights Reserved.
*/

#include <common.h>
#include <command.h>
#include <malloc.h>
#include <asm/string.h>
#include <ubnt_api_calls.h>
#include <version_autogenerated.h>
#include <net.h>

#define UNUSED(x) ((void)(x))
#define UBNT_CMD_MAX_ARG 7
#define UBNT_CMD_MAX_LEN 24
#define UBNT_CMD_STR_MAX 48

#define UBNT_APP_MAGIC 0x87564523

extern unsigned long uboot_end_data;
extern unsigned long _start;

    /* Loads the application into memory */

int ubnt_app_load()
{
    char addr[10];

    ulong ubntapp_flash_addr = CFG_FLASH_BASE +
                               ((ulong)&uboot_end_data - (ulong)&_start);

    /* If the ubnt application is not loaded yet, load it now */
    memmove((void *) UBNT_APP_MAGIC_OFFSET, (void *)ubntapp_flash_addr,
            UBNT_APP_SIZE);

    if (UBNT_APP_MAGIC != *((uint32_t *)UBNT_APP_MAGIC_OFFSET)) {
        printf(" *WARNING*: UBNT APP Magic mismatch, addr=%x, magic=%x \n",
               ((uint32_t *)UBNT_APP_MAGIC_OFFSET),
               *((uint32_t *)UBNT_APP_MAGIC_OFFSET));
        return -1;
    }

    sprintf(addr, "%x", UBNT_APP_START_OFFSET);
    setenv("ubntaddr", addr);

    return 0;
}

#define VERSION_LEN_MAX 128
/* The SSID is located after two 6-byte MAC addresses */
#define UBNT_SSID_OFFSET 12

uint8_t prepare_beacon(uint8_t *buf) {
    uint8_t *pkt = buf;
    uint8_t *len_p;

    // Lengths
    uint8_t total_len;
    uint8_t header_len;
    uint8_t body_len;

    // U-Boot Version
    char *version = U_BOOT_VERSION;
    uint8_t version_len = strlen(version);
    if (version_len > VERSION_LEN_MAX)
        version_len = VERSION_LEN_MAX;

    // SSID
    uint16_t *ubnt_ssid_p = (uint16_t *) (BOARDCAL + UBNT_SSID_OFFSET);

    /* header */
    *pkt++ = 0x03; // version
    *pkt++ = 0x07; // type (net rescue beacon)
    len_p = pkt++; // beacon size
    *pkt++ = 0x03; // bootloader version

    header_len = pkt - buf;

    /* uboot */
    *pkt++ = version_len;
    memcpy(pkt, version, version_len);
    pkt += version_len;

    /* board */
    memcpy(pkt, ubnt_ssid_p, sizeof(*ubnt_ssid_p));
    pkt += sizeof(*ubnt_ssid_p);

    total_len = pkt - buf;
    body_len = total_len - header_len;

    // Include size in beacon.
    *len_p = body_len;

    return total_len;
}
